---
Gemfile:
  supports_windows: true
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
appveyor.yml:
  matrix_extras:
    - PUPPET_GEM_VERSION: 3.7.0
      RUBY_VER: 193
    - PUPPET_GEM_VERSION: 3.7.0
      RUBY_VER: 200-x64

